### ISSUE TITLE
ERROR 500 sending messages

### ISSUE THREAD

**Issue by aleex42** [Robertof/perl-www-telegram-botapi#12]
Hello,

from time to time I'm getting an ERROR 500 while sending my messages:

`ERROR: 500 Can't connect to api.telegram.org:443 at lib/WWW/Telegram/BotAPI.pm line 204.`

Any idea how to automaticly retry sending this message (which works fine via hand)? I've got no idea how to get this error state in my perl script.

Thanks for helping!

Best regards,
Alex

**Comment by Robertof** [comment]
Hi,

thanks for using this module!

You should be able to use `eval` or even the `parse_error` method to do what you asked for. Here's an example:

``` perl
# suppose you have a `WWW::Telegram::BotAPI` object in $api
my ($tries, $result) = 0;
while ($tries++ < 3) {
  $result = eval { $api->method ($params) }; # <- your API call goes here
  if (my $raw_error = $@) {
    my $error = $api->parse_error ($raw_error);
    # $error->{type} can be "api" for API-related errors or "agent" for agent-related errors (network, ...)
    # You may want to retry only errors coming from the user agent.
    die "ERROR: got error of type ", $error->{type}, ": ", $error->{msg}
      if $error->{type} ne "agent";
    die "ERROR: got error after 3 retries: ", $error->{msg}, ". Giving up!"
      if $tries >= 3;
    say STDERR "WARNING: something went wrong! Got: ", $error->{msg};
    say STDERR "Starting try #@{[$tries + 1]}...";
    # You may want to implement waiting here like...
    # sleep (2);
    next;
  }
  last; # Do not retry if the request is successful. This is important!
}
# Do something with $result...
```

Hope it helps!
Roberto

**Comment by Robertof** [comment]
I haven't heard back from you since 1 month, so I'm closing this issue.

If there's anything else you need, let me know.

Happy holidays!
Roberto
