### ISSUE TITLE
How to use http proxy with your module

### ISSUE THREAD

**Issue by DRVTiny** [Robertof/perl-www-telegram-botapi#14]
Hello!

Is this possible to get UserAgent object instance used by your module and tell it to use proxy?

This feature may look like this:

my $api = WWW::Telegram::BotAPI->new('token'=>'123456');
my $ua = $api->getUserAgent;
$ua->env_proxy;

After this trick my $api object will use $ENV{'https_proxy'} to send requests to the Telegram BotAPI server.

Is it possible to use HTTPS proxy with your API now (with the current version of your module)?

Thanks!

**Comment by Robertof** [comment]
Sure. Take a look at [`WWW::Telegram::BotAPI->agent`](https://metacpan.org/pod/WWW::Telegram::BotAPI#agent), which allows you to get an instance of the agent. You will then be responsible to correctly set the proxy whether it is a `LWP::UserAgent` or a `Mojo::UserAgent` instance,
Be aware that Telegram uses HTTPS! As an example:
```perl
my $agent = $api->agent;
if ($agent->isa ("LWP::UserAgent")) {
  # Use LWP::Protocol::connect (for https)
  $agent->proxy ("https", "...");
} else {
  # Mojo::UserAgent (builtin)
  $agent->proxy->https ("...");
}
```

**Comment by DRVTiny** [comment]
That works perfectly. Thank you!

**Comment by Robertof** [comment]
Glad that it worked out for you! Cheers :+1:
