### ISSUE TITLE
ERROR: Bad Gateway

### ISSUE THREAD

**Issue by DRVTiny** [Robertof/perl-www-telegram-botapi#17]
Glad to greet you again! :)

Now i use your package as a backend (working in async mode) for my Telebot2, which code was inspired moistly by your answer to my previous issue posted here.

Unfortunately after many hours  (about 10 hours) of running my program using Telebot2, which doing nothing than initialize and use your module - i got "ERROR: Bad Gateway". After the second crash of my program i run it with TELEGRAM_BOTAPI_DEBUG=1, so maybe i can get some more information about this exception. I guess this is Mojo::UserAgent issue.

Now waiting for program sudden dead :) Maybe, you have some assumption about what can be wrong? Hint: i have to use corporate proxy server to connect to telegram api. 

I'll post all collected debug info  here after crash.

**Comment by DRVTiny** [comment]
-T- END REQUEST to /getUpdates (async) :: Tue Apr 18 21:53:04 2017
-T- BEGIN REQUEST to /getUpdates :: Tue Apr 18 21:53:34 2017
PAYLOAD = [
   "https://api.telegram.org/botXXXXXXXXX/getUpdates",
   "json",
   {  
      "timeout" : 30,
      "allowed_updates" : [
         "message"
      ]
   }
]
-T- END REQUEST to /getUpdates (async) :: Tue Apr 18 21:53:34 2017
-T- BEGIN REQUEST to /getUpdates :: Tue Apr 18 21:54:05 2017
PAYLOAD = [
   "https://api.telegram.org/botXXXXXXXXX/getUpdates",
   "json",
   {  
      "timeout" : 30,
      "allowed_updates" : [
         "message"
      ]
   }
]
-T- END REQUEST to /getUpdates (async) :: Tue Apr 18 21:54:05 2017
-T- BEGIN REQUEST to /getUpdates :: Tue Apr 18 21:54:35 2017
PAYLOAD = [
   "https://api.telegram.org/botXXXXXXXXX/getUpdates",
   "json",
   {  
      "timeout" : 30,
      "allowed_updates" : [
         "message"
      ]
   }
]
-T- END REQUEST to /getUpdates (async) :: Tue Apr 18 21:54:35 2017
ERROR: Bad Gateway

**Comment by Robertof** [comment]
Hi again! I'm sorry for the delayed answer.

I actually think that you are either witnessing downtime in the bot API (less likely) or in your corporate proxy server (more likely).

A `Bad Gateway`, which is a server-side error (and as such not derived from this module), indicates that a server behind a frontend proxy server is down. I suspect this could be derived from your corporate proxy, but I'm just guessing.

Does this happen consistently every 10 hours?

Thanks!

**Comment by Robertof** [comment]
I haven't heard back from you for a while. Hope everything worked out for you, so for now I'm closing this issue.

Thanks!

**Comment by realsergii** [comment]
Similar (same?) issue happens to me:

2018-10-31 03:17:23,591 - telegram.ext.updater - ERROR - Error while getting Updates: Bad Gateway
2018-10-31 03:17:23,606 - _main_ - WARNING - Update "None" caused error "Bad Gateway"

I don't use proxy. The issue happens systematically after my bot is running for around 10 hours. Even when nobody is using it.

However I'm using Python version.

**Comment by Robertof** [comment]
I think these are just momentary (maybe scheduled?) downtimes of Telegram's Bot API, which shouldn't be linked to client-side implementations (such as my module or the one you're using). If you look around by searching "telegram api bad gateway" there are other reports about it.
Have a good day!

**Comment by realsergii** [comment]
> I think these are just momentary (maybe scheduled?) downtimes of Telegram's Bot API, which shouldn't be linked to client-side implementations (such as my module or the one you're using). If you look around by searching "telegram api bad gateway" there are other reports about it.
> Have a good day!

What would you recommend to cope with such things?

**Comment by Robertof** [comment]
It should not be too hard to extract the HTTP error code after receiving the error and - if and only if it's a 503 - automatically retry after a given period of time. This module already allows to get the HTTP error code and in another issue provided some example code to retry after something goes wrong. I think this is the cleanest and easier solution to handle such a situation.

Have a good day,
Roberto
