### ISSUE TITLE
 ERROR: code 404: Not Found

### ISSUE THREAD

**Issue by tuwid** [Robertof/perl-www-telegram-botapi#20]
Hi,
tried to run the sample script with perl 5.26 and it dies as follows:
```
Starting monxms_monx-bot_1 ... done
Attaching to monxms_monx-bot_1
monx-bot_1  | ERROR: code 404: Not Found at /usr/local/lib/perl5/site_perl/5.26.1/WWW/Telegram/BotAPI.pm line 209.
monx-bot_1  | 	WWW::Telegram::BotAPI::api_request() called at /usr/local/lib/perl5/site_perl/5.26.1/WWW/Telegram/BotAPI.pm line 76
monx-bot_1  | 	WWW::Telegram::BotAPI::AUTOLOAD(WWW::Telegram::BotAPI=HASH(0x55772ae52390)) called at router_bot.pl line 14
monxms_monx-bot_1 exited with code 255
```
The format I pass the token is botXXXXX:XXXXXXXXX-XXXXXXXXXXXX ( maybe is related to that )

Any ideas

**Comment by Robertof** [comment]
Hi,

the token shouldn't contain the prefix `bot` (it's automatically prefixed by the BotAPI). It should be exactly the same as the one BotFather gives you.

Let me know if that works for you,
Roberto

**Comment by Robertof** [comment]
I hope your problem was successfully solved! I'm closing the issue for inactivity, but please let me know if any other issue occurs. 😄 

Have a nice day!
