### ISSUE TITLE
Possible issue with Cpanel::JSON::XS::encode_json?

### ISSUE THREAD

**Issue by polettix** [Robertof/perl-www-telegram-botapi#21]
Hi,

I got [this interesting test failure](http://www.cpantesters.org/cpan/report/eac57ea2-0922-11e8-a1cf-bb670eaac09d) in a module that uses WWW::Telegram::BotAPI behind the scenes, the most relevant part being:

    Error:  Too many arguments for Cpanel::JSON::XS::encode_json at \
    .../WWW-Telegram-BotAPI-0.09/blib/lib/WWW/Telegram/BotAPI.pm \
    line 176, near "or"

I though you might be interested into it.

**Comment by Robertof** [comment]
Hi!

Thanks for your report. 
That is indeed a curious issue, and I think that it is caused by the lack of parentheses around the call to encode_json. The strange thing is that it's only happening now - - maybe something related to Cpanel::JSON::XS?

I'll look into it, however I am not at home right now. I'll let you know!

Thanks,
Roberto

**Comment by polettix** [comment]
Hi!

I received more reports. I didn't look into each of them, but a few samples showed the same exact problem. See list at the bottom of this message.

One interesting thing I noticed is this:

	  Module Name                        Have     Want
	  Bot::ChatBots                     0.006    0.006
	  IO::Socket::SSL                   2.054    2.038
          ...
	  WWW::Telegram::BotAPI              0.09     0.07
	  namespace::clean                   0.27     0.27

So... `WWW::Telegram::BotAPI` is *already* installed in the system (my prerequisite is `0.07` but they already have `0.09`), so I suspect something might have happened in the meantime, like installation of `Cpanel::JSON::XS` (or its upgrade) in the test system.

Whatever, I think that this construct is likely to bite anyway (why it doesn't trigger an error in the general case still being a mystery):

            $is_lwp
                and push @request, DEBUG ? (DBG => $postdata) : (), # handled in _fix_request_args
                                   Content      => JSON::MaybeXS::encode_json $postdata,
                                   Content_Type => "application/json"
                or  push @request, json         => $postdata;

My guess is that `Content_Type => "application/json"` and following might be considered parameters to `encode_json`, not to the `push`, depending on how `encode_json` is defined. Some change in this definition might have changed cards on the table.

I personally feel a bit uneasy looking at the construct with `and` and `or`, somehow too *cleverish*. Just personal taste anyway.

It's also weird that these reports are all *bsd related.

Bot-ChatBots-Telegram-0.011-TRIAL:
- amd64-freebsd / 5.22.0:
  - FAIL http://www.cpantesters.org/cpan/report/b77bfda2-08a3-11e8-a1cf-bb670eaac09d

- amd64-freebsd-thread-multi / 5.22.0:
  - FAIL http://www.cpantesters.org/cpan/report/4a24f99a-08c9-11e8-a1cf-bb670eaac09d

- amd64-netbsd / 5.22.3:
  - FAIL http://www.cpantesters.org/cpan/report/d591d5e4-08aa-11e8-9abe-a171f40b351c

- amd64-netbsd / 5.22.4:
  - FAIL http://www.cpantesters.org/cpan/report/86fdd4c8-08d7-11e8-9abe-a171f40b351c

- amd64-netbsd / 5.24.0:
  - FAIL http://www.cpantesters.org/cpan/report/64403822-08ff-11e8-9abe-a171f40b351c

- amd64-netbsd / 5.24.1:
  - FAIL http://www.cpantesters.org/cpan/report/1837350e-0911-11e8-a1cf-bb670eaac09d

- amd64-netbsd / 5.24.2:
  - FAIL http://www.cpantesters.org/cpan/report/821da4c2-08ed-11e8-a1cf-bb670eaac09d

- amd64-netbsd / 5.24.3:
  - FAIL http://www.cpantesters.org/cpan/report/b282ef34-08c8-11e8-a1cf-bb670eaac09d

- amd64-netbsd-thread-multi / 5.22.2:
  - FAIL http://www.cpantesters.org/cpan/report/dcaa263a-0894-11e8-9abe-a171f40b351c

- amd64-netbsd-thread-multi / 5.22.3:
  - FAIL http://www.cpantesters.org/cpan/report/d8e1afea-08c2-11e8-9abe-a171f40b351c

- amd64-netbsd-thread-multi / 5.22.4:
  - FAIL http://www.cpantesters.org/cpan/report/0072c55c-08ec-11e8-9abe-a171f40b351c

- amd64-netbsd-thread-multi / 5.24.0:
  - FAIL http://www.cpantesters.org/cpan/report/d486b968-0912-11e8-9abe-a171f40b351c

- amd64-netbsd-thread-multi / 5.24.1:
  - FAIL http://www.cpantesters.org/cpan/report/eac57ea2-0922-11e8-a1cf-bb670eaac09d

- amd64-netbsd-thread-multi / 5.24.2:
  - FAIL http://www.cpantesters.org/cpan/report/7bd65b06-08ff-11e8-a1cf-bb670eaac09d

- amd64-netbsd-thread-multi / 5.24.3:
  - FAIL http://www.cpantesters.org/cpan/report/aa1b24fc-08db-11e8-a1cf-bb670eaac09d

**Comment by Robertof** [comment]
Hey,

yep - you traced the issue exactly where I did yesterday, and my guess is the same as yours. 
The strange thing is that existing tests should have caught this before it even became a problem. I will make sure that this won't happen again.

Thanks for your detailed report anyway! I am also aware that I relied too much on obscure Perl precedence rules, and I confess that I am kind of obsessed on those things :p 

I am still away from a keyboard so I can't immediately fix this. I will do it ASAP.
Thanks again for the comprehensive report, and obviously for being a fellow user of this module!

P.S. orgoglio italiano! Felice di sapere che qualche italiano Perlista c'è!

**Comment by polettix** [comment]
Ciao Roberto,

I can propose a pull request if you want, by just putting parentheses while calling that function. This might speed you up a bit.

The module is very useful and I like it's somehow future proof.

PS: eh siamo in pochi apparentemente. Come gruppo sembra quasi che siamo scoppiati dopo aver organizzato YAPC a Pisa!

**Comment by Robertof** [comment]
Hey,

It's not really necessary! I'll gladly avoid you the hassle of forking the repo and doing the PR. I should be able to push a fixed version in just a few hours where I will finally have access to a keyboard.

Thanks for your appreciation!

Non seguo molto gli eventi della community Italiana di Perl, anche perché spesso sono organizzati un po' lontano. Ma un giorno mi piacerebbe incontrarvi tutti!

Rob

**Comment by henkvantijen** [comment]
I am in favor of a YAPC::EU in the Pisa/Lucca area!  :-)
perl + good food & wine..

**Comment by Robertof** [comment]
Hey,

I just released v0.10 that should solve this issue once and for all :D It should land on CPAN shortly.
Thanks again Flavio for your thoroughness and kindness!

P.S. I'm all for a new YAPC conference here in Italy, sign me up! 🍺
