### ISSUE TITLE
ERROR: SSL connect attempt failed due to Telegram blocking in Russia

### ISSUE THREAD

**Issue by pavelsr** [Robertof/perl-www-telegram-botapi#24]
Bot stopped working 7 days ago, seems like it's related with Telegram blocking in Russia.

Error message is:
```
ERROR: SSL connect attempt failed
 at /usr/local/share/perl/5.20.2/WWW/Telegram/BotAPI.pm line 208.
	WWW::Telegram::BotAPI::api_request() called at /usr/local/share/perl/5.20.2/WWW/Telegram/BotAPI.pm line 76
	WWW::Telegram::BotAPI::AUTOLOAD(WWW::Telegram::BotAPI=HASH(0x2a64c28)) called at bot_embedded.pl line 212
```

Is there any built-it WWW::Telegram::BotAPI capabilities for blocking interlock like setting up proxy servers or using alternative network interface for connection?

**Comment by Robertof** [comment]
Hi there!

I'm sorry you're having issues due to geo-blocking of Telegram. Proxies are indeed supported by the underlying `agent`s, see https://github.com/Robertof/perl-www-telegram-botapi/issues/14.

Hope this can help solve your problems.
Cheers!

**Comment by Robertof** [comment]
I'm closing this as it's been a while, let me know if you need further help :)

Cheers!
