### ISSUE TITLE
Method not found "say $api->getMe->{result}{username};"

### ISSUE THREAD

**Issue by emakei** [Robertof/perl-www-telegram-botapi#25]
And with
``` perl
my $result = eval { $api->getMe }
    or die 'Got error message: ', $api->parse_error->{msg};
say $result->username; #$result->result->username;
```
Can't call method "say" on unblessed reference

**Comment by LuisDiazUgena** [comment]
say is a perl 5.0 function. If you're using an older version of perl you should use print instead.

**Comment by emakei** [comment]
perl 5.26.1 on Windows (both git-bash and Strawbetty Perl)
With `print` I see something like `HASH(0x8238..)`

**Comment by henkvantijen** [comment]
5.10 , me thinks.  Enable with
    use v5.10;

**Comment by Robertof** [comment]
Yeah, `say` is a Perl feature that has to be enabled manually. You can also do:

```perl
use feature 'say';
```

Let me know if that helped you.
Cheers!

**Comment by Robertof** [comment]
Also, now that I'm looking carefully, note that you must use hash dereferences and not method calls to retrieve the fields.
This is ok:
```perl
use feature 'say';
my $result = eval { $api->getMe }
    or die 'Got error message: ', $api->parse_error->{msg};
say $result->{result}{username};
```

Taking a look at the example bot may also be useful for you: https://gist.github.com/Robertof/d9358b80d95850e2eb34

**Comment by emakei** [comment]
It's works, thanks!

**Comment by Robertof** [comment]
No problem, have a good day!
