### ISSUE TITLE
How to get messages from users and conversation id

### ISSUE THREAD

**Issue by LuisDiazUgena** [Robertof/perl-www-telegram-botapi#26]
Hi!

I'm not sure if this is possible with this, but, how to get messages from users? Also, is there any way to get the data from the conversation-id?

Thanks

**Comment by Robertof** [comment]
Hi,

check out the example bot here: https://gist.github.com/Robertof/d9358b80d95850e2eb34
And the official documentation of the bot API to learn more about Telegram data structures: https://core.telegram.org/bots/api

Let me know if that helped you.
Cheers!

**Comment by LuisDiazUgena** [comment]
Thanks so much, that seems to have everything that I need for creating my bot.

**Comment by Robertof** [comment]
You're welcome! Thanks for using the module.

**Comment by LuisDiazUgena** [comment]
Thanks you for creating it. Still don't get how to use this:

```
for my $u (@{$updates->{result}}) {
        $offset = $u->{update_id} + 1 if $u->{update_id} >= $offset;
        if (my $text = $u->{message}{text}) { # Text message
            printf "Incoming text message from \@%s\n", $u->{message}{from}{username};
            printf "Text: %s\n", $text;
            next if $text !~ m!^/[^_].!; # Not a command
            my ($cmd, @params) = split / /, $text;
            my $res = $commands->{substr ($cmd, 1)} || $commands->{_unknown};
            # Pass to the subroutine the message object, and the parameters passed to the cmd.
            $res = $res->($u->{message}, @params) if ref $res eq "CODE";
            next unless $res;
            my $method = ref $res && $res->{method} ? delete $res->{method} : "sendMessage";
            $api->$method ({
                chat_id => $u->{message}{chat}{id},
                ref $res ? %$res : ( text => $res )
            });
            print "Reply sent.\n";
        }
        # Handle other message types.
        for my $type (keys %{$u->{message} || {}}) {
            next unless exists $message_types->{$type} and
                        ref (my $res = $message_types->{$type}->($u->{message}));
            my $method = delete ($res->{method}) || "sendMessage";
            $api->$method ({
                chat_id => $u->{message}{chat}{id},
                %$res
            })
        }
    }
```
Would try to find howto in the next days. Thanks

**Comment by Robertof** [comment]
Hi,

what the bot is doing - except standard business logic operations - is just using the official [bot API methods](https://core.telegram.org/bots/api#getting-updates).

It calls `getUpdates` which returns a list of `Update` objects (you can see their structure in the link I attached), checks if they are recent enough to be considered by us (by comparing the `update_id` to the last we have saved), then does different actions based on the message type.

The first condition, for instance, checks if the received message is a text message, prints out the text, filters out non-commands (messages not starting with `/`), and then checks if in the `$commands` hash there's an associated handler for that command. If so, it replies with what the handler says.

That's basically it! I suggest reading the official Telegram bot api documentation which provides insights about how to deal with the API itself and also about the structure of the objects.
