### ISSUE TITLE
Add inline bots support

### ISSUE THREAD

**Issue by emakei** [Robertof/perl-www-telegram-botapi#27]
There is inline bots (https://core.telegram.org/bots/inline). It will be great to have this feature.

**Comment by Robertof** [comment]
Technically it's already possible to implement inline bots! Remember that this module supports any method defined in the Bot API spec, and inline queries are given as an update in `getUpdates`. You jut need to code it!

**Comment by Robertof** [comment]
I'm closing this, let me know if you need further help :)

Cheers!
