### ISSUE TITLE
Mojo::Transaction::success is DEPRECATED warnings

### ISSUE THREAD

**Issue by huckeduster** [Robertof/perl-www-telegram-botapi#28]
In the latest major Mojolicious version (8.x) `Mojo::Transaction::success` was deprecated and will probably be removed in the next major version entirely (https://github.com/mojolicious/mojo/issues/1266).

Running the examples gives me the following warning message:

```
$ perl 01_send_message.pl
Mojo::Transaction::success is DEPRECATED in favor of Mojo::Transaction::result and Mojo::Transaction::error at /Users/*****/.plenv/versions/5.28.1-********/lib/perl5/site_perl/5.28.1/WWW/Telegram/BotAPI.pm line 200.
```

A possible fix is described in the already mentioned Mojolicious issue (https://github.com/mojolicious/mojo/issues/1266).

**Comment by Robertof** [comment]
Hey,

thank you for your report -- much appreciated!
I'll deploy a fix for this in a few hours.

Thanks,
Roberto

**Comment by Robertof** [comment]
I just deployed v0.11 on CPAN, it should be available shortly. Thanks for your contribution and for using the module!
