### ISSUE TITLE
ERROR: Proxy connection failed - print details

### ISSUE THREAD

**Issue by pavelsr** [Robertof/perl-www-telegram-botapi#29]
Hi, Roberto. I think it would be nice to print proxy connection error more verbose.

Example.

```
/app # echo $https_proxy
https://51.158.186.141:8080/

/app # MOJO_PROXY=1 MOJO_CLIENT_DEBUG=1 MOJO_EVENTEMITTER_DEBUG=1 perl tg.pl
-- Blocking request (https://api.telegram.org/botXXXXXXXXXXXX/getMe)
-- Emit prepare in Mojo::UserAgent (0)
-- Emit start in Mojo::UserAgent (0)
-- Emit prepare in Mojo::UserAgent (0)
-- Emit start in Mojo::UserAgent (0)
-- Connect 9951afbd78600392637ec703384c87b1 (https://api.telegram.org:443)
-- Emit error in Mojo::IOLoop::TLS (1)
-- Emit error in Mojo::IOLoop::Client (1)
-- Emit finish in Mojo::Message::Response (0)
-- Emit finish in Mojo::Transaction::HTTP (0)
-- Emit finish in Mojo::Message::Response (0)
-- Emit finish in Mojo::Transaction::HTTP (0)
ERROR: Proxy connection failed at /usr/local/share/perl5/site_perl/WWW/Telegram/BotAPI.pm line 209.
	WWW::Telegram::BotAPI::api_request() called at /usr/local/share/perl5/site_perl/WWW/Telegram/BotAPI.pm line 76
	WWW::Telegram::BotAPI::AUTOLOAD(WWW::Telegram::BotAPI=HASH(0x55b090419f50)) called at tg.pl line 17

/app # curl -vL https://example.org/
* Uses proxy env variable https_proxy == 'https://51.158.186.141:8080/'
*   Trying 51.158.186.141:8080...
* TCP_NODELAY set
* connect to 51.158.186.141 port 8080 failed: Connection refused
* Failed to connect to 51.158.186.141 port 8080: Connection refused
* Closing connection 0
curl: (7) Failed to connect to 51.158.186.141 port 8080: Connection refused
```

**Comment by Robertof** [comment]
Hi Pavel,

happy new year! I'm very sorry for the late response but it's been a busy period -- thanks for using my module.

So as you might know the entire proxy handling is done by `Mojo::UserAgent`, and what I do is to just print out the error that Mojo returns. You can see the lines which generate the error here:

https://github.com/mojolicious/mojo/blob/1e8ed18e79025e0e7dc1f2a50a37da6e0fb048c9/lib/Mojo/UserAgent.pm#L155-L157

I'll try to investigate this a bit further and see if I can accommodate your request, though. I'll let you know!

**Comment by Robertof** [comment]
Hey! I got great news.

I was able to find a way to intercept the real reason of failure for proxy errors and I have pushed 2f6a791 (which will soon be in version 0.12 on CPAN) which will print these kind of failures when using debug mode (i.e. `TELEGRAM_BOTAPI_DEBUG=1`).

If you need the actual proxy failure in code and not when debugging, then you can retrieve the `Mojo::UserAgent` instance from the module and perform the same process that I'm doing. It would look like:

```perl
# assuming $api is a WWW::Telegram::BotAPI object
my $agent = $api->agent;
if ($agent->isa ('Mojo::UserAgent')) { # Only related to Mojo::UserAgent
    $agent->on (start => sub {
        my (undef, $tx) = @_;
        # Skip all requests which are not proxy-related.
        return unless $tx->req->method eq "CONNECT";
        # Add an handler on completion.
        $tx->on (finish => sub {
            my $tx = shift;
            if (my $error = $tx->error) {
                # $error is an hash reference with "message" in it. Do whatever you need with that information.
                say "Kaboom! ", $error->{message};
            }
        });
    })
}
```

Hope this has been useful. Feel free to reopen the issue if anything else comes up!

Have a good day,
Roberto

**Comment by pavelsr** [comment]
Great, Roberto, thanks so much!
