### ISSUE TITLE
ERROR:  500 Can't connect to api.telegram.org:443

### ISSUE THREAD

**Issue by mrdengue** [Robertof/perl-www-telegram-botapi#30]
Hi Roberto!,

Since yesterday all my bots are receiving this error message:

-T- WWW::Telegram::botBotAPI initialized (v0.12), using agent LWP::UserAgent synchronously.
-T- BEGIN REQUEST to /getMe :: Thu Feb  6 12:02:20 2020
PAYLOAD = [
   "https://api.telegram.org/botXXXXXXXXX/getMe"
]
RESPONSE = undefined
ERROR: 500 Can't connect to api.telegram.org:443 

When in happened, I thought it was a connection issue, BUT if I connect to the API vía  curl, it works!... So  I  Upgraded  from 0.11 to 0.12 with no luck.  All bots stopped at the same time, around 8:30AM yesterday.  

Are you aware if there's an issue with de module?

Thanks in advance,
Jorge

**Comment by asos-robertofrenna** [comment]
Hello Jorge,

thanks for using the module!

I am not aware of any issues with the module to be fair, and it indeed looks like some kind of connection issue. Do you have any environment variables related to proxies set by chance?

Also, you might want to try to use the other user agent. If you can install Perl modules, try installing `Mojo::UserAgent` and rerunning the bot in debug mode again -- you should see "using agent Mojo::UserAgent synchronously".

Keep me posted!
Thanks,
Roberto

**Comment by Robertof** [comment]
Hello Jorge,

thanks for using the module!

I am not aware of any issues with the module to be fair, and it indeed looks like some kind of connection issue. Do you have any environment variables related to proxies set by chance?

Also, you might want to try to use the other user agent. If you can install Perl modules, try installing Mojo::UserAgent and rerunning the bot in debug mode again -- you should see "using agent Mojo::UserAgent synchronously".

Keep me posted!
Thanks,
Roberto

EDIT: just to be sure I just tried to run a bot from my home connection, and it seems like it worked correctly.

**Comment by mrdengue** [comment]
Hello Roberto!....

Thanks for your response...  I installed Mojolicious as requested and got a SSL error:

-T- WWW::Telegram::botBotAPI initialized (v0.12), using agent Mojo::UserAgent synchronously.
-T- BEGIN REQUEST to /getMe :: Thu Feb  6 13:01:22 2020
PAYLOAD = [
   "https://api.telegram.org/botXXXXXXXXX/getMe"
]
RESPONSE = undefined
ERROR: SSL connect attempt failed error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

**Comment by Robertof** [comment]
Interesting, this looks like it might be due to an old version of `Net::SSLeay`. Could you try running:

```sh
perl -MNet::SSLeay -E 'say Net::SSLeay::SSLeay_version(0)'
```

Thanks!

**Comment by mrdengue** [comment]
Hi Roberto...  Two things:

1) perl -MNet::SSLeay -E 'say Net::SSLeay::SSLeay_version(0)'
OpenSSL 1.0.2g  1 Mar 2016

2) For some reason I got this message last night from Telegram BotNews Channel:
Please note that the Bot API only accepts incoming TLS 1.2 connections (or higher). Kindly update your bot if it was using the outdated TLS 1.0 or TLS 1.1 protocol.

Maybe WHAT I need to do is make sure That Net::SSLeay uses TLS1.2?

What do you think?

**Comment by mrdengue** [comment]
Ok, it seems to be working now:

I upgraded Net:SSLeay and LWP::Protocol::https

So both are using OpenSSL 1.1.1 now!
I also had to install a valid CA certificate, which I didn't have because I was using getUPdates instead of webhook.  
Also I ditched LWP and now I'm using Mojolicious. 

I hope this helps to anyone having this issue!

**Comment by Robertof** [comment]
Hey @mrdengue, that's what I was going to suggest! Sorry for not getting back to you in time, but I'm happy you were able to solve the issue.

Thanks a lot for your detailed report of your findings, and have a good day!
