### ISSUE TITLE
How to send requests like: users.getUsers, messages.reportSpam

### ISSUE THREAD

**Issue by KES777** [Robertof/perl-www-telegram-botapi#32]
I can not find anywhere how to do requests to [this part](https://core.telegram.org/methods) of telegram API

For all I get `404 Not Found`

Can you add documentation for this?

**Comment by Robertof** [comment]
Hi!

Thanks for using this module. The methods you linked above are unfortunately reserved for the MTProto-based Telegram API (i.e., the one used by the main clients using Telegram's proprietary protocol). The methods available to use via the Bot API are [only the ones specified in the official section of the documentation](https://core.telegram.org/bots/api).

If what you need to do is not something the Bot API can do for you, then you will need to use MTProto. There are many implementations available online (though I'm not sure there is one available for Perl).

Hope this helps - I'm going to close the issue but let me know if you have any other doubt.
Thanks!
