### ISSUE TITLE
File resend (file_id use)

### ISSUE THREAD

**Issue by x09** [Robertof/perl-www-telegram-botapi#4]
Hi,

> File uploads are specified using an hash reference containing the following mappings:
>   file => '/path/to/file.ext'
>   Path to the file you want to upload.
> 
>    Required only if content is not specified.
>    filename => 'file_name.ext'
>    An optional filename that will be used instead of the real name of the file.
>    Particularly recommended when content is specified.
> 
>    content => 'Being a file is cool :-)'
>   The content of the file to send. When this is used, file must not be specified.
> 
>    AnyCustom => 'Header'
>    Custom headers can be specified as hash mappings.

If i want resend photo using file_id?

1) file_id as value instead file path - error

```
    $api->SendPhoto ({
    chat_id => 123456,
    photo => {
            file => 'AgADAgAD0qcxG-FUEAABy5Zu7WIBvtSmjIQqAATR-BDeru8bpD0FAAIC' ,
            },
    caption => 'test'
    })
```

2) file_id as field - error

```
   $api->SendPhoto ({
    chat_id => 123456,
    photo => {
            file_id => 'AgADAgAD0qcxG-FUEAABy5Zu7WIBvtSmjIQqAATR-BDeru8bpD0FAAIC' ,
            },
    caption => 'test'
    })
```

why?

**Comment by Robertof** [comment]
Just do:

``` perl
$api->sendPhoto ({
    chat_id => 123456,
    photo   => 'your id',
    caption => 'test'
});
```

**Comment by x09** [comment]
```
...
$commands = {
"start"  => sub { $api->SendPhoto({ chat_id => shift->{chat}{id}, caption=>'started', photo=>'AgADAgAD0qcxG-FUEAABy5Zu7WIBvtSmjIQqAATR-BDeru8bpD0FAAIC' }); return },
.... 
other commands below
....
```

get error

```
ERROR: 400 Bad Request at /usr/lib/perl5/site_perl/5.8.8/WWW/Telegram/BotAPI.pm line 140.
    WWW::Telegram::BotAPI::api_request(undef, undef, HASH(0x11bebf10)) called at /usr/lib/perl5/site_perl/5.8.8/WWW/Telegram/BotAPI.pm line 49
    WWW::Telegram::BotAPI::AUTOLOAD(WWW::Telegram::BotAPI=HASH(0x11237f70), HASH(0x11bebf10)) called at ./reedBot.v2.pl line 289              
    main::__ANON__(HASH(0x11a23420)) called at ./reedBot.v2.pl line 334  
```

**Comment by Robertof** [comment]
Sorry for the late answer, I had some health issues.

By the way, it works on my side. I have also updated `tg-bot-example.pl` with an example.

https://gist.github.com/Robertof/d9358b80d95850e2eb34
