### ISSUE TITLE
unicode in keyboad show wrong on windows

### ISSUE THREAD

**Issue by ldktta** [Robertof/perl-www-telegram-botapi#7]
First congratulations for the good work in this module.

i found a bug on windows.

i put in a keyboad a unicode  like this '💉'.

the bot running on windows show wrong characters on keyboard. like this '≡ƒæô'

the same bot running on linux show unicode in keyboard well.

I tested several conversions of characters and types , always with the same wrong result on windows.

thanks.-

**Comment by Robertof** [comment]
Hi!

May I know which version of Perl are you currently using? Are you using like Strawberry Perl, or ActivePerl?
Are you using the latest version of the module?

Thank you.
Roberto

**Comment by ldktta** [comment]
Hi, Roberto

i use Active Pert 5.20 64 bits on Windows 10
and use the latest version of this module ( v0.03  installed with ppm )

feel free to ask me any other data you need.
thank you

**Comment by Robertof** [comment]
Are you storing the character in the bot's source?
Try using a different text editor (e.g. Sublime Text, Notepad++, whatever) and save the file with the UTF-8 encoding.

**Comment by ldktta** [comment]
yes in de souce, i use sublime Text and save whit UTF-8.

bot send the normal response whit unicodes and they look well. 

the problem only occurs when use keyboard whit unicodes. 

example:

( [ [ "💢", "💢" ] ] )

the same unicode 💢 look good when the response is a text message.

**Comment by Robertof** [comment]
How are you encoding the keyboard JSON content? With `JSON::MaybeXS`?

If you are using that module, maybe there's a problem with its implementation on Win32. You could try:

``` perl
JSON::MaybeXS->new (utf8 => 1)->encode ({ ... })
```

**Comment by ldktta** [comment]
tried but the same error. :(

**Comment by Robertof** [comment]
It looks like an issue with their port of `JSON::MaybeXS` then. Try specifying the keyboard markup by hand, like:

``` perl
{ reply_markup => '{"keyboard":[["🐱", "🐎"]]}' }
```

This is obviously **without** using `JSON::MaybeXS`!

**Comment by ldktta** [comment]
no way., only dirty characters.... 
proves in others windows sistem and tell you later the result.

I am increasingly convinced that this is a problem in Windows 10 and Perl.

.meanwhile  migrate the bot to linux. 

thanks

**Comment by Robertof** [comment]
That's strange. I was pretty sure that the problem was actually caused by an encoding issue.

I will setup an ActivePerl environment tomorrow to see if I can reproduce the issue.
Good night!

**Comment by ldktta** [comment]
iam unistall perl and re-instal the latest version Active Perl 5.22.1, and now work fine.

It does not know why , but now look unicodes fine

sorry for the discomfort and thank you for the help. 
Once again thank you for everything and for this great module.

**Comment by Robertof** [comment]
Alrighty then, you're welcome!
